//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FireboyAndWatergirl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FireboyAndWatergirl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bkgdFbWg {
            get {
                object obj = ResourceManager.GetObject("bkgdFbWg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;level&gt;
        ///   &lt;platform&gt;
        ///      &lt;x&gt;20&lt;/x&gt;
        ///      &lt;y&gt;700&lt;/y&gt;
        ///      &lt;width&gt;900&lt;/width&gt;
        ///      &lt;height&gt;25&lt;/height&gt;
        ///      &lt;type&gt;platform&lt;/type&gt;
        ///   &lt;/platform&gt;
        ///   &lt;platform&gt;
        ///      &lt;x&gt;500&lt;/x&gt;
        ///      &lt;y&gt;520&lt;/y&gt;
        ///      &lt;width&gt;900&lt;/width&gt;
        ///      &lt;height&gt;25&lt;/height&gt;
        ///      &lt;type&gt;platform&lt;/type&gt;
        ///   &lt;/platform&gt;
        ///   &lt;platform&gt;
        ///      &lt;x&gt;300&lt;/x&gt;
        ///      &lt;y&gt;340&lt;/y&gt;
        ///      &lt;width&gt;900&lt;/width&gt;
        ///      &lt;height&gt;25&lt;/height&gt;
        ///      &lt;type&gt;platform&lt;/type&gt;
        ///   &lt;/platform&gt;
        ///   &lt;platform&gt;
        ///      &lt;x&gt;20&lt;/x&gt;
        ///      &lt;y&gt;1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string level1_xml {
            get {
                return ResourceManager.GetString("level1.xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap platformImg {
            get {
                object obj = ResourceManager.GetObject("platformImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
